import math as m

print("sin 30 =", m.sin(m.radians(30)))
print("sin 45 =", m.sin(m.radians(45)))
print("sin 60 =", m.sin(m.radians(60)))
print("sin 90 =", m.sin(m.radians(90)))
print("\n")
print("sinh 30 =", m.sinh(m.radians(30)))
print("sinh 45 =", m.sinh(m.radians(45)))
print("sinh 60 =", m.sinh(m.radians(60)))
print("sinh 90 =", m.sinh(m.radians(90)))
print("\n")
print("asin 0 =", m.degrees(m.asin(0)))
print("asin 0.5 =", m.degrees(m.asin(0.5)))
print("asin 0.7 =", m.degrees(m.asin(0.7)))
print("asin 1 =", m.degrees(m.asin(1)))
print("\n")
print("acos 0 =", m.degrees(m.acos(0)))
print("acos 0.5 =", m.degrees(m.acos(0.5)))
print("acos 0.7 =", m.degrees(m.acos(0.7)))
print("acos 1 =", m.degrees(m.acos(1)))
print("\n")
print("atan 0 =", m.degrees(m.atan(0)))
print("atan 0.5 =", m.degrees(m.atan(0.5)))
print("atan 0.7 =", m.degrees(m.atan(0.7)))
print("atan 1 =", m.degrees(m.atan(1)))
